### ISSUE TITLE
mariadb connection

### ISSUE THREAD

**Issue by lhoumeau** [IshtarStar/docker-compose-nginx-phpfpm-xdebug-mariadb#5]
Hello,

Container built after .env update (for mariadb variables).
I can connect to the database with Sequel Ace. I cannot connect with the PHP instruction: new PDO( $dsn, $user, $password); with variables declared in .env file.

Fatal error thrown:

Fatal error: Uncaught PDOException: SQLSTATE[HY000] [2002] Connection refused in /app/src/public/index.php ...

An idea?

Regards

laurent

**Comment by IshtarStar** [comment]
Hello Laurent,

Thank you for reporting the issue.

The "Connection refused" error typically occurs when the PHP container cannot communicate with the MariaDB container. Here are a few steps to troubleshoot and resolve the issue:

1. **Check Database Host in DSN:**
   Ensure that the host in your DSN string is set to `mariadb`, not `localhost` or `127.0.0.1`, since the database is running in a separate container. The connection string might look like this:

   ```php
   $dsn = 'mysql:host=mariadb;dbname=' . getenv('MARIADB_DATABASE');
   $user = getenv('MARIADB_USER');
   $password = getenv('MARIADB_PASSWORD');
   ```

   This is because Docker uses service names to handle internal networking between containers.

2. **Ensure .env Variables Are Loaded in PHP-FPM:**
   Make sure that the `.env` file variables are correctly loaded in the PHP-FPM container. You can add the `.env` file as a volume to your `php-fpm` service to make sure those variables are accessible:

   ```yaml
   services:
     php-fpm:
       # other configurations...
       env_file:
         - .env
   ```

3. **Verify the MariaDB Connection:**
   - Try to connect to MariaDB from within the PHP-FPM container to verify network communication. You can do this by entering the PHP-FPM container using:
     ```bash
     docker-compose exec php-fpm sh
     ```
     Then, attempt to connect to MariaDB using `mysql`:
     ```bash
     mysql -u $MARIADB_USER -p -h mariadb
     ```

4. **Check MariaDB Logs:**
   Check if MariaDB is running without issues by inspecting the logs. Run:
   ```bash
   docker-compose logs mariadb
   ```
   Ensure that the database starts correctly and that there are no errors related to user authentication.

Let me know if this helps resolve the issue or if you encounter further problems!

Best regards,  
Marc

**Comment by lhoumeau** [comment]
Hello Marc.

Thank you for your very useful reply. It's now ok. The "host=mariadb" was the solution (and not "host=127.0.0.1").

I'm newcomer with containerisation/docker. Previously, I worked with ubuntu VMs (1 for nginx/php/redis, 1 for mariadb) on MacOS/Parallel Desktop.

After many try (and fails due to php extensions, in particular PDO...), I was very interested in your full stack project.

IMHO, if you have some time, may be can you improve it with a complete (and short) example.php as checker for Redis (ping), mariadb (PDO connexion to a "test" database), and a composer use case (within php-fpm container). It will be useful for a number of people.

Best regards,

laurent
